<!doctype html>
<html>
<head>
<meta charset="utf-8">
<title>Documento sem título</title>
<style>
	table{color: rgb(0,152,216);font-weight: 400;font-size: 11pt;font-family:verdana}	
	.tab-in td{padding:0px;border: solid 1px #E70000}
	.tab-in td td{padding:3px;border:0;border-right:solid 1px #E70000;}
	.tab-in td td:last-child{border:0}
	.tab-in td td td{padding:0;border:0}
	.tab-in .td-in{padding: 0}
	.tab-in .td-in td{padding: 0px;border-right: solid 1px #E70000}
	.td-fix{padding:3px !important}
	
</style>
</head>

<body onLoad="print()">
<table width="1000" border="0" align="center" cellpadding="0" cellspacing="0" style="overflow: wrap"  autosize="1" >
  <tbody>
    <tr>
      <td style="padding: 15px"><table width="100%" border="0" cellspacing="0" cellpadding="0">
        <tbody>
          <tr>
            <td width="200" valign="top"><img src="{logo}" width="180" height="70" alt=""/></td>
            <td align="center"><p>Rua Belo Horizonte 809, Centro, Londrina-PR- Brasil. CEP 86020-060 Tel.: (43) 3361-6177 - <br>
www.doorsenglish.com </p>
              <p><br>
                <strong>CONTRATO DE PRESTAÇÃO DE SERVIÇOS </strong></p>
              <p>&nbsp;</p></td>
            <td width="200">&nbsp;</td>
          </tr>
        </tbody>
      </table>
        <p>Pelo presente instrumento particular, e na melhor forma de  direito, de um lado o responsável especificado no quadro de informações na  folha oposta, denominado simplesmente CONTRATANTE, e de outro, a DOORS CENTRO  DE IDIOMAS LTDA - EPP, pessoa jurídica de direito privado inscrita no CNPJ/MF  sob o nº 26.480.075/0001- 00, estabelecida na Rua Belo Horizonte, nº 809,  Centro, Londrina-PR, doravante simplesmente denominada CONTRATADA, tem entre si  certo e ajustado com a livre manifestação da vontade, a contratação dos  serviços para o aprendizado do idioma inglês o qual se regerá pelas cláusulas e  condições a seguir estabelecidas:</p>
        <p><br>
        <strong>Cláusula I</strong> - A vigência do presente instrumento será de 26  meses a contar da data de sua primeira aula. Parágrafo primeiro - A Contratada  irá prestar os serviços para o aprendizado do idioma inglês colocando-se à  disposição do contratante dentro do período de funcionamento da contratada, que  é das 8h às 22h de segunda-feira a sexta-feira e das 9h às 17h aos sábados.</p>
        <p><br>
        Parágrafo segundo - A duração de cada hora/aula ministrada  na sede da contratada terá a duração de 50 minutos, conforme regulamentado pela  portaria 887 /52, pareceres CFE 459/85 e 28/92 e repetidas convenções  coletivas, fornecidos pelo sindicato dos professores da cidade de Londrina-PR.</p>
        <p><br>
        Parágrafo terceiro - O Contratante poderá trancar o curso pelo  período máximo de 60 dias (corridos ou fracionados) através de requerimento de  trancamento preenchido e assinado pessoalmente pelo mesmo na sede da  contratada, desde que não exista pendência financeira com a escola e ciente de  que neste período de trancamento seus deveres financeiros com a contratada deverão  ser cumpridos normalmente.</p>
        <p><br>
        Parágrafo quarto - O período de trancamento quando requerido  pelo contratante será reposto ao final do presente contrato, prorrogando-o pelo  mesmo período de dias solicitado sem custo adicional, e o contratante será  remanejado em outra turma após o período de ausência, se necessário.</p>
        <p><br>
        <strong>Cláusula II</strong> - O contratante terá que cumprir com todo  cronograma de ensino da contratada, inclusive testes, provas, tarefas e  atividades extra classe.</p>
        <p><br>
        Parágrafo único - Somente quando o contratante concluir o  cronograma do curso e obtiver a nota mínima de 7 ,O pontos em todas avaliações,  o mesmo obterá a aprovação e receberá um certificado de conclusão do curso de  inglês da Doors English Center.</p>
        <p><br>
        <strong>Cláusula III</strong> - O contratante tem o conhecimento de que, se  no decorrer do contrato ocorrer a redução do número de alunos na turma,  inferior a 6 (seis) alunos, a contratada reserva a si o direito de remanejar e  ou transferir estes alunos para outras turmas de mesmo nível sem o prejuízo  para os mesmos.</p>
        <p><br>
        Parágrafo único - O contratante também tem o conhecimento de  que se houver o acúmulo de 2 (duas) faltas ou 2 (duas) aulas desmarcadas no  mesmo mês, a contratada poderá se houver necessidade, transferir o contratante  para outra turma e até mesmo para outros horários.</p>
        <p><br>
        <strong>Cláusula IV</strong> - O contratante deverá desmarcar suas aulas  quando necessário com a antecedência de até 4 (quatro) horas dentro dos  horários de funcionamento da instituição conforme descrito na cláusula I,  parágrafo primeiro. O não comparecimento incidirá o pagamento de multa no valor  de R$ 20,00 (vinte reais) por aula, que deverá ser pago até sua próxima aula e  inclusive em caso de rescisão contratual.</p>
        <p><br>
        <strong>Cláusula V</strong> - O material didático é de uso individual,  obrigatório e intransferível, não estando incluso no valor das parcelas do  curso, devendo ser adquirido pelo contratante na sede da contratada pelo valor  total de R$ 1040,00 (hum mil e quarenta reais), compondo 4 (quatro) livros,  sendo utilizado um a cada módulo de aproximadamente 6 (seis) meses, e poderão  ser pagos de forma integral ou em parcelas a combinar com a contratada.</p>
        <p><br>
        Parágrafo único: Fica expressamente proibida a reprodução,  por qualquer meio ou forma, do material didático fornecido pela contratada,  conforme a Lei nº 610/98, o contratante ainda tem ciência de que, por motivo  pessoal, não adquirir o material didático, ficará impedido de ter sua presença  em aula tendo que remarcar a aula perdida após a compra de seu material.</p>
        <p><br>
        <strong>Cláusula VI</strong> - A contratada prestará os serviços para o  aprendizado do idioma inglês ao contratante pelo valor total de R$ 6.580,00  (seis mil e quinhentos e oitenta reais), que deverá ser pago da seguinte forma:</p>
        <p><br>
          A) R$ 340,00 (trezentos e quarenta reais) a título de  matricula.<br>
        B)  24 (vinte e  quatro) parcelas fixas e mensais cada uma no valor de R$ 260,00 ( duzentos e  sessenta reais) vencíveis nos dias ____ de cada mês, a serem pagas através de boleto  bancário sendo a primeira parcela com vencimento em __ / __ / __ .</p>
        <p><br>
        Parágrafo único: Quaisquer benefícios tais como:  abatimentos, descontos e/ou redução de parcelas através de requerimento de  crédito estudantil vinculado ao presente contrato, constituem mera liberalidade  da contratada, não caracterizando novação ou renuncia de direitos. </p>
        <p><br>
        <strong>Cláusula VII</strong> - Os direitos e obrigações do presente contrato  serão cumpridos independentes da frequência do contratante às aulas, pois, o  não comparecimento não o exime do pagamento das parcelas descritas na cláusula  VI, tendo em vista que o serviço é prestado e colocado à sua disposição  independente da sua utilização. </p>
        <p><br>
        Parágrafo único: por ser um serviço que é prestado e  colocado à disposição, as partes atribuem ao presente contrato plena eficácia e  força executiva extrajudicial. </p>
        <p><br>
        <strong>Cláusula VIII</strong> - O valor da matrícula é pago a título de  inscrição e tem a finalidade de custear a abertura de cadastro administrativo,  impostos e encargos gerados e não será devolvido em caso de rescisão  contratual. </p>
        <p><br>
        <strong>Cláusula IX</strong> - Para rescindir o contrato, o contratante ou  responsável quando menor, deverá o fazer pessoalmente na sede da contratada e  preencher o documento de rescisão contratual, estando quite com valores  anteriores a data da rescisão tais como, matrícula, parcelas, e multas  hora/aula, pagar a parcela do mês em que se der a rescisão e a multa contratual  no valor de uma parcela do item B da cláusula VI do presente contrato. </p>
        <p><br>
        Parágrafo primeiro - Se a data da rescisão contratual  ocorrer antes do vencimento da primeira parcela descrita no item B da cláusula  VI, o contratante deverá pagar uma multa contratual referente ao valor de 10% (dez  por cento) sobre o valor total descrito na cláusula VI do presente contrato. </p>
        <p><br>
        Parágrafo segundo - Não serão aceitas solicitações de  rescisão contratual por telefone, e-mail, ou outro diferente do caput desta  cláusula. </p>
        <p><br>
        <strong>Cláusula X</strong> - O contratante ou responsável declara  expressamente que tem conhecimento de que não terá direito a restituição de  valores pagos a título de matrícula, material didático e parcelas quitadas; principalmente  onde o contratante se beneficia de descontos, abatimentos e/ou redução de  parcelas através de requerimento de crédito estudantil vinculado ao presente  contrato, independente de rescisão contratual. </p>
        <p><br>
        <strong>Cláusula XI</strong> - Em caso de inadimplência, será aplicado o  índice de 2% (dois por cento) sobre o valor devido além de 1 % (um por cento)  ao mês até a data do efetivo pagamento. </p>
        <p><br>
        Parágrafo primeiro - em caso de inadimplência onde o  contratante se beneficie de descontos, abatimentos e/ou redução de parcelas,  através de requerimento de credito estudantil vinculado ao presente contrato,  acarretará a perda do abatimento ou desconto especificado no referido mês em  atraso, e será praticado o valor especificado no item B da cláusula VI. </p>
        <p><strong><br>
        Cláusula XII</strong> - O contratante declara expressamente que tem  conhecimento de que eventual inadimplência, independente de rescisão  contratual, será comunicado ao serviço de proteção ao crédito e Serasa, nos  termos da seção VI, do capítulo V, do Código de Defesa do Consumidor (Lei 8.078/90),  e que o presente contrato será protestado em cartório. </p>
        <p><br>
        <strong>Cláusula XIII</strong> - As partes atribuem ao presente contrato  plena eficácia e força extrajudicial, independente de prévia notificação. </p>
        <p><br>
        <strong>Cláusula XIV</strong> - Fica eleito o foro da cidade de Londrina-PR,  para dirimir quaisquer dúvidas oriundas do presente contrato que é assinado em  duas vias.</p></td>
    </tr>
    <tr>
      <td align="center"  style="padding: 15px"><p>Londrina, __ / __ / _____ </p></td>
    </tr>
    <tr>
      <td  style="padding: 15px"><table width="100%" border="0" cellspacing="0" cellpadding="0">
        <tbody>
          <tr>
            <td align="center"><p>__________________________________<br>
              Contratante</p></td>
            <td align="center"><p>__________________________________<br>
              Contratada </p></td>
          </tr>
          <tr>
            <td align="center"><p><br>
                <br>
                <br>
                __________________________________<br>
              Responsável </p>
              <p>&nbsp;</p></td>
            <td align="center"><p><br>
                <br>
                <br>
                __________________________________<br>
              Representante </p>
              <p>&nbsp;</p></td>
          </tr>
        </tbody>
      </table>
        </td>
    </tr>
  </tbody>
</table>
<table width="1000" border="1" class="tab-in" cellspacing="0" align="center" cellpadding="0" style="border: solid 1px #C50000;border-collapse: collapse;margin-top:100px">
          <tbody>
            <tr>
              <td width="50%" colspan="5" bgcolor="#E7F8FF" class="td-fix">Aluno: {nome}</td>
              <td width="50%" bgcolor="#E7F8FF"  class="td-fix">Endereço: {endereco}</td>
            </tr>
            <tr>
              <td colspan="5" bgcolor="#E7F8FF"><table width="100%" border="0" cellspacing="0" cellpadding="0">
                <tbody>
                  <tr>
                    <td height="22">CPF: {cpf}</td>
                    <td>RG: {rg}</td>
                  </tr>
                </tbody>
              </table></td>
              <td bgcolor="#E7F8FF"><table width="100%" border="0" cellspacing="0" cellpadding="0">
                <tbody>
                  <tr>
                    <td>Número: <span class="td-fix">{numero}</span></td>
                    <td>Compl.: <span class="td-fix">{complemento}</span></td>
                    </tr>
                  </tbody>
              </table></td>
            </tr>
            <tr>
              <td bgcolor="#E7F8FF"   class="td-fix">Data Nascimento: {nascimento}</td>
              <td bgcolor="#E7F8FF"   class="td-fix" >Masculino:</td>
              <td width="20" align="center" bgcolor="#E7F8FF"  class="td-in">{sm}</td>
              <td bgcolor="#E7F8FF"  class="td-fix">Feminino:</td>
              <td width="20" align="center" bgcolor="#E7F8FF"  class="td-in">{sf}</td>
              <td bgcolor="#E7F8FF"><table width="100%" border="0" cellspacing="0" cellpadding="0">
                <tbody>
                  <tr>
                    <td>Bairro: <span class="td-fix">{bairro}</span></td>
                    <td>CEP: <span class="td-fix">{cep}</span></td>
                  </tr>
                </tbody>
              </table></td>
            </tr>
            <tr>
              <td height="20" colspan="5" bgcolor="#E7F8FF"><table width="100%" border="0" cellspacing="0" cellpadding="0">
                <tbody>
                  <tr>
                    <td>Profissão: {profissao}</td>
                    <td>Empresa: {empresa}</td>
                  </tr>
                </tbody>
              </table></td>
              <td bgcolor="#E7F8FF"><table width="100%" border="0" cellspacing="0" cellpadding="0">
                <tbody>
                  <tr>
                    <td>Cidade: <span class="td-fix">{cidade}</span></td>
                    <td>Estado: <span class="td-fix">{estado}</span></td>
                    </tr>
                  </tbody>
              </table></td>
            </tr>
            <tr>
              <td colspan="5" bgcolor="#E7F8FF"><table width="100%" border="0" cellspacing="0" cellpadding="0">
                <tbody>
                  <tr>
                    <td>Tel. Fixo: {telefone_fixo}</td>
                    <td>Celular: {celular}</td>
                  </tr>
                </tbody>
              </table></td>
              <td bgcolor="#E7F8FF"><table width="100%" border="0" cellspacing="0" cellpadding="0">
                <tbody>
                  <tr>
                    <td>Tel.Comercial: <span class="td-fix">{telefone_comercial}</span></td>
                    <td>Outro: <span class="td-fix">{telefone_outro}</span></td>
                    </tr>
                  </tbody>
              </table></td>
            </tr>
            <tr>
              <td colspan="6" bgcolor="#E7F8FF"  class="td-fix">E-mail: {email}</td>
            </tr>
            <tr>
              <td colspan="5" bgcolor="#E7F8FF"  class="td-fix">Responsável: {nome_responsavel}</td>
              <td width="50%" bgcolor="#E7F8FF"  class="td-fix">Endereço: {endereco_responsavel}</td>
            </tr>
            <tr>
              <td colspan="5" bgcolor="#E7F8FF"><table width="100%" border="0" cellspacing="0" cellpadding="0">
                <tbody>
                  <tr>
                    <td>CPF: {cpf_responsavel}</td>
                    <td>RG: {rg_responsavel}</td>
                    </tr>
                  </tbody>
              </table></td>
              <td bgcolor="#E7F8FF"><table width="100%" border="0" cellspacing="0" cellpadding="0">
                <tbody>
                  <tr>
                    <td>Número: <span class="td-fix">{numero_responsavel}</span></td>
                    <td>Compl.: <span class="td-fix">{complemento_responsavel}</span></td>
                    </tr>
                  </tbody>
              </table></td>
            </tr>
            <tr>
              <td bgcolor="#E7F8FF"  class="td-fix">Data Nascimento: {nascimento_responsavel}</td>
              <td bgcolor="#E7F8FF"><span  class="td-fix">Masculino:</span></td>
              <td width="20" align="center" bgcolor="#E7F8FF"><span class="td-in">{sm_responsavel}</span></td>
              <td bgcolor="#E7F8FF"><span  class="td-fix">Feminino:</span></td>
              <td width="20" align="center" bgcolor="#E7F8FF">{sf_responsavel}</td>
              <td bgcolor="#E7F8FF"><table width="100%" border="0" cellspacing="0" cellpadding="0">
                <tbody>
                  <tr>
                    <td>Bairro: <span class="td-fix">{bairro_responsavel}</span></td>
                    <td>CEP: <span class="td-fix">{cep_responsavel}</span></td>
                    </tr>
                  </tbody>
              </table></td>
            </tr>
            <tr>
              <td colspan="5" bgcolor="#E7F8FF"><table width="100%" border="0" cellspacing="0" cellpadding="0">
                <tbody>
                  <tr>
                    <td>Profissão: {profissao_responsavel}</td>
                    <td>Empresa: {empresa_responsavel}</td>
                    </tr>
                  </tbody>
              </table></td>
              <td bgcolor="#E7F8FF"><table width="100%" border="0" cellspacing="0" cellpadding="0">
                <tbody>
                  <tr>
                    <td>Cidade: <span class="td-fix">{cidade_responsavel}</span></td>
                    <td>Estado: <span class="td-fix">{estado_responsavel}</span></td>
                    </tr>
                  </tbody>
              </table></td>
            </tr>
            <tr>
              <td colspan="5" bgcolor="#E7F8FF"><table width="100%" border="0" cellspacing="0" cellpadding="0">
                <tbody>
                  <tr>
                    <td>Tel. Fixo: {telefone_fixo_responsavel}</td>
                    <td>Celular: {celular_responsavel}</td>
                  </tr>
                </tbody>
              </table></td>
              <td bgcolor="#E7F8FF"><table width="100%" border="0" cellspacing="0" cellpadding="0">
                <tbody>
                  <tr>
                    <td>Tel.Comercial: <span class="td-fix">{telefone_comercial_responsavel}</span></td>
                    <td>Outro: <span class="td-fix">{telefone_outro_responsavel}</span></td>
                    </tr>
                  </tbody>
              </table></td>
            </tr>
            <tr>
              <td colspan="6" bgcolor="#E7F8FF"  class="td-fix">E-mail: {email_responsavel}</td>
            </tr>
            <tr>
              <td colspan="6" bgcolor="#E7F8FF"  class="td-fix">Observações: </td>
            </tr>
            <tr>
              <td colspan="6" bgcolor="#E7F8FF"  class="td-fix">&nbsp;</td>
            </tr>
            <tr>
              <td colspan="6" bgcolor="#E7F8FF"  class="td-fix">&nbsp;</td>
            </tr>
            <tr>
              <td colspan="5" bgcolor="#E7F8FF"  class="td-fix">Star Class (primeira aula): &nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; /&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;/&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; às &nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; : &nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; h.</td>
              <td bgcolor="#E7F8FF"><table width="100%" border="0" cellspacing="0" cellpadding="0">
                <tbody>
                  <tr>
                    <td>Turma fixa semanal: </td>
                    <td width="20">seg</td>
                    <td width="15">&nbsp;</td>
                    <td>ter</td>
                    <td width="15">&nbsp;</td>
                    <td>qua</td>
                    <td width="15">&nbsp;</td>
                    <td>qui</td>
                    <td width="15">&nbsp;</td>
                    <td>sex</td>
                    <td width="15">&nbsp;</td>
                    <td>sab</td>
                    <td width="15">&nbsp;</td>
                    </tr>
                  </tbody>
              </table></td>
            </tr>
            <tr>
              <td colspan="5" style="border: 0 !important"  class="td-fix">Uso Administrativo</td>
              <td bgcolor="#E7F8FF"><table width="100%" border="0" cellspacing="0" cellpadding="0">
                <tbody>
                  <tr>
                    <td>Horário das aulas: &nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;:&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;h</td>
                    <td>Início da turma: &nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;/&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;/&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; </td>
                    </tr>
                  </tbody>
              </table></td>
            </tr>
            <tr>
              <td colspan="5" bgcolor="#E7F8FF"><table width="100%" border="0" cellspacing="0" cellpadding="0">
                <tbody>
                  <tr>
                    <td>ID: {matricula}</td>
                    <td>Plano: {plano}</td>
                  </tr>
                </tbody>
              </table></td>
              <td bgcolor="#E7F8FF"><table width="100%" border="0" cellspacing="0" cellpadding="0">
                <tbody>
                  <tr>
                    <td>Matrícula:</td>
                    <td>Data:</td>
                    </tr>
                  </tbody>
              </table></td>
            </tr>
            <tr>
              <td colspan="5" bgcolor="#E7F8FF"  class="td-fix">1ª Parcela  dia: &nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;/&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; /&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; forma:</td>
              <td bgcolor="#E7F8FF"  class="td-fix">2ª parcela dia &nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;/&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; /&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; forma:</td>
            </tr>
            <tr>
              <td colspan="5" bgcolor="#E7F8FF"><table width="100%" border="0" cellspacing="0" cellpadding="0">
                <tbody>
                  <tr>
                    <td width="25%">Responsáveis:</td>
                    <td width="25%">&nbsp;</td>
                    <td width="25%">&nbsp;</td>
                    <td width="25%">&nbsp;</td>
                  </tr>
                </tbody>
              </table></td>
              <td bgcolor="#E7F8FF"><table width="100%" border="0" cellspacing="0" cellpadding="0">
                <tbody>
                  <tr>
                    <td width="25%">&nbsp;</td>
                    <td width="25%">&nbsp;</td>
                    <td width="25%">Registrado por:</td>
                    <td width="25%">&nbsp;</td>
                    </tr>
                  </tbody>
              </table></td>
            </tr>
          </tbody>
      </table>
</body>
</html>
