<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit78b0b444bfa195e844d473688f15728e
{
    public static $files = array (
        '04c6c5c2f7095ccf6c481d3e53e1776f' => __DIR__ . '/..' . '/mustangostang/spyc/Spyc.php',
    );

    public static $prefixLengthsPsr4 = array (
        'C' => 
        array (
            'Cnab\\' => 5,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Cnab\\' => 
        array (
            0 => __DIR__ . '/..' . '/andersondanilo/cnab_php/src/Cnab',
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit78b0b444bfa195e844d473688f15728e::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit78b0b444bfa195e844d473688f15728e::$prefixDirsPsr4;

        }, null, ClassLoader::class);
    }
}
